name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: sitkoru/php7-ci
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: composer install
    - name: phpstan
      run: bash phpstan.sh
